

#R2 variables
Thumbnail.Access.Key.ID=${THUMBNAILACCESSKEYID}
Thumbnail.Token.value=${THUMBNAILTOKENVALUE}
Thumbnail.Secret.Access.Key=${THUMBNAILSECRETACCESSKEY}
R2.URL=${R2URL}


#clamAV variables
clamAV.URI=${CLAMAVURI}
clamAV.Port=%${CLAMAVPORT}