server.port=${SERVERPORT}

#R2 variables
Thumbnail.Access.Key.ID=${THUMBNAILACCESSKEYID}
Thumbnail.Token.value=${THUMBNAILTOKENVALUE}
Thumbnail.Secret.Access.Key=${THUMBNAILSECRETACCESSKEY}
R2.URI=${R2URI}
First.Bucket.Name=${FIRSTBUCKETNAME}


#clamAV variables
clamAV.URI=${CLAMAVURI}
clamAV.Port=${CLAMAVPORT}

#Kafka Variables
kafka.filescan.topic=${KAFKAFILESCANTOPIC}
kafka.port=${KAFKAPORT}

